---
name: activemodel
version: '7.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 3cdcbea7f7a2a2ba5dffce3ee71f938f8b301687
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
